services:
  postgres:
    image: postgis/postgis
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hshl
    volumes:
      - ti-postgres-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@hshl.de
      - PGADMIN_DEFAULT_PASSWORD=hshl
    volumes:
      - ti-pgadmin-data:/var/lib/pgadmin/

volumes:
  ti-postgres-data:
  ti-pgadmin-data: