version: "3"

services:
  postgres:
    image: imresamu/postgis-arm64
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=hshl
    volumes:
      - ti-postgres-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@hshl.de
      - PGADMIN_DEFAULT_PASSWORD=hshl
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgadmin4/pgpass

volumes:
  ti-postgres-data:
