services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - todo-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@hshl.de
      - PGADMIN_DEFAULT_PASSWORD=secret
    volumes:  
      - todo-config:/var/lib/pgadmin/
  
  dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    environment:
      - Dashboard__Frontend__BrowserToken=ctCP3AkvOguAhWDKuXFCbHbU1F62kxJ0
    ports:
      - 18888:18888
      - 18889:18889

volumes:
  todo-data:
  todo-config: