# Um dieses Script bei jeder Änderung auszuführen, müsste diese Datei unter /.github/workflows abgelegt werden
name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest-cov pylint-exit
        if [ -f hshl/wp/04/requirements.txt ]; then pip install -r hshl/wp/04/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint hshl/wp/04/test_project/ --disable=C0111 || pylint-exit $?
    - name: Test the code with pytest
      run: |
        pytest --cov=test_project --cov-fail-under=90 --cov-branch hshl/wp/04/test_project/