apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: second-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: second-app
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
