# Basis-Image
FROM imresamu/postgis-arm64

LABEL maintainer="stuckenholz"

# Install necessary packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        build-essential \
        postgresql-server-dev-all \
    && rm -rf /var/lib/apt/lists/*

# Install pgvector
RUN cd /tmp && \
    git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    make && \
    make install && \
    cd / && \
    rm -rf /tmp/pgvector

# Create SQL script to initialize the extension
RUN echo "CREATE EXTENSION IF NOT EXISTS vector;" > /docker-entrypoint-initdb.d/pgvector.sql