version: "3"

services:
  postgres:
    image: postgis/postgis
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@wb-fernstudium.de
      - PGADMIN_DEFAULT_PASSWORD=secret
    volumes:
      - pgadmin-config:/var/lib/pgadmin/

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana 

volumes:
  postgres-data:
  pgadmin-config:
  influx-data:
  grafana-data:

  